# Site settings
title: Anya
author: Anya
email: nick@firedev.com
description: > # this means to ignore newlines until "baseurl:"
    Hello my name is Anya I like to draw, paint and swim. I am living in
    Phuket, Thailand with my mom and dad.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://firedev.github.io/anya" # the base hostname & protocol for your site

# Build settings
permalink: pretty
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "Rakefile"

tag_title_prefix: ''
tag_title_suffix: ''
tag_dir: ''

highlighter: pygments
