# Site settings
title: firedev.com
author: firedev
email: nick@firedev.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://firedev.github.io" # the base hostname & protocol for your site
twitter_username: firedev
github_username: firedev

# Build settings
permalink: pretty
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "Rakefile"

tag_title_prefix: ''
tag_title_suffix: ''
tag_dir: ''

highlighter: pygments
